# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/mytest-project',
                'doc_host': 'https://Novosib123.github.io',
                'git_url': 'https://github.com/Novosib123/mytest-project',
                'lib_path': 'mytest_project'},
  'syms': { 'mytest_project\\card': { 'mytest_project\\card.Card': ('card.html#card', 'mytest_project\\card.py'),
                                      'mytest_project\\card.Card.__init__': ('card.html#__init__', 'mytest_project\\card.py'),
                                      'mytest_project\\card.Card.__str__': ('card.html#__str__', 'mytest_project\\card.py')},
            'mytest_project\\core': {'mytest_project\\core.foo': ('core.html#foo', 'mytest_project\\core.py')}}}